# Generated by Django 4.0.4 on 2022-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('binary_data', models.BinaryField()),
            ],
        ),
    ]
